---
title: "CodeBook"
author: "Miguel Prata"
date: "20 de Maio de 2015"
output: html_document
---

#Introduction

This is the codebook for the data set created for this assignement. The data set is called `tidy`.

#Data dictionary

**SubjectNumber**   -- Test subject number. Varies from 1 to 30.

**Activity** -- Activity being performed while measurements were made. Can be:

* Lying
* Sitting
* Standing
* Walking
* Walking Downstairs
* Walking Upstairs

The other columns contain all the variable means and standard deviations. Their names are the same as the ones in the **features.txt** (see README.Rmd), However, in order to use the `select` function in R, invalid character names were removed with `make.name`, so for example, the variable,

**tBodyAcc-mean()-X** becomes **tBodyAcc.mean...X**

**tBodyAcc.mean...X**

**tBodyAcc.mean...Y**

**tBodyAcc.mean...Z**

**tGravityAcc.mean...X**

**tGravityAcc.mean...Y**

**tGravityAcc.mean...Z**

**tBodyAccJerk.mean...X**

**tBodyAccJerk.mean...Y**

**tBodyAccJerk.mean...Z**

**tBodyGyro.mean...X**

**tBodyGyro.mean...Y**

**tBodyGyro.mean...Z**

**tBodyGyroJerk.mean...X**

**tBodyGyroJerk.mean...Y**

**tBodyGyroJerk.mean...Z**

**tBodyAccMag.mean..**

**tGravityAccMag.mean..**

**tBodyAccJerkMag.mean..**

**tBodyGyroMag.mean..**

**tBodyGyroJerkMag.mean..**

**fBodyAcc.mean...X**

**fBodyAcc.mean...Y**

**fBodyAcc.mean...Z**

**fBodyAccJerk.mean...X**

**fBodyAccJerk.mean...Y**

**fBodyAccJerk.mean...Z**

**fBodyGyro.mean...X**

**fBodyGyro.mean...Y**

**fBodyGyro.mean...Z**

**fBodyAccMag.mean..**

**fBodyBodyAccJerkMag.mean..**

**fBodyBodyGyroMag.mean..**

**fBodyBodyGyroJerkMag.mean..**

**tBodyAcc.std...X**

**tBodyAcc.std...Y**

**tBodyAcc.std...Z**

**tGravityAcc.std...X**

**tGravityAcc.std...Y**

**tGravityAcc.std...Z**

**tBodyAccJerk.std...X**

**tBodyAccJerk.std...Y**

**tBodyAccJerk.std...Z**

**tBodyGyro.std...X**

**tBodyGyro.std...Y**

**tBodyGyro.std...Z**

**tBodyGyroJerk.std...X**

**tBodyGyroJerk.std...Y**

**tBodyGyroJerk.std...Z**

**tBodyAccMag.std..**

**tGravityAccMag.std..**

**tBodyAccJerkMag.std..**

**tBodyGyroMag.std..**

**tBodyGyroJerkMag.std..**

**fBodyAcc.std...X**

**fBodyAcc.std...Y**

**fBodyAcc.std...Z**

**fBodyAccJerk.std...X**

**fBodyAccJerk.std...Y**

**fBodyAccJerk.std...Z**

**fBodyGyro.std...X**

**fBodyGyro.std...Y**

**fBodyGyro.std...Z**

**fBodyAccMag.std..**

**fBodyBodyAccJerkMag.std..**

**fBodyBodyGyroMag.std..**

**fBodyBodyGyroJerkMag.std..**

Please refer to **features.txt** for the meaning of each variable.